name: massai mara park 01 dockerfile build

on:
  workflow_dispatch:

jobs:
  mmpark01_dockerfile_build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: massai_mara:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker container
        run: |
          docker run -d --name mmpark -p 8080:8080 massai_mara:v1
          sleep 20
          echo "Running containers:"
          docker ps
          echo "Container logs:"
          docker logs mmpark

      - name: Run automated test #1
        run: |
          echo "Running Test 1"
          curl --fail http://localhost:8080

      - name: Run automated test #2
        run: |
          echo "Running Test 2"
          curl --fail http://localhost:8080

      - name: Run automated test #3
        run: |
          echo "Running Test 3"
          curl --fail http://localhost:8080