name: massai mara park 01 compose build

on:
  workflow_dispatch:

jobs:
  mmpark01_compose_build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Docker Compose Version
        run: docker compose version

      - name: Build with Docker Compose
        run: docker compose build

      - name: Run with Docker Compose
        run: |
          docker compose up -d
          sleep 30
          docker compose ps
          docker compose logs

      - name: Run Automated Test #1
        run: |
          echo "Running Test 1"
          curl --fail http://localhost:8080

      - name: Run Automated Test #2
        run: |
          echo "Running Test 2"
          curl --fail http://localhost:8080

      - name: Run Automated Test #3
        run: |
          echo "Running Test 3"
          curl --fail http://localhost:8080
